# Generated by Django 4.2.20 on 2025-05-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_generaluser_first_name_generaluser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaluser',
            name='profile_image',
            field=models.URLField(default='https://www.flaticon.com/free-icon/profile-picture_12225881?term=profile&related_id=12225881'),
        ),
    ]
