# Generated by Django 4.2.20 on 2025-05-20 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_dataset_files_dataset_downloads_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likesandviews',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='likesandviews',
            name='user',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.generaluser'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='likesandviews',
            unique_together={('user', 'dataset')},
        ),
        migrations.RemoveField(
            model_name='likesandviews',
            name='username',
        ),
    ]
