# Generated by Django 4.2.20 on 2025-05-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_likesandviews_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='profile_image',
            field=models.CharField(),
        ),
    ]
