# Generated by Django 4.2.20 on 2025-05-20 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_dataset_owner_alter_generaluser_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesAndViewsDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('viewed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataItr', to='api.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataItr', to='api.generaluser')),
            ],
            options={
                'unique_together': {('user', 'dataset')},
            },
        ),
        migrations.CreateModel(
            name='LikesAndViewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('viewed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='mlmodel',
            old_name='dataset_type',
            new_name='model_type',
        ),
        migrations.RemoveField(
            model_name='mlmodel',
            name='files_count',
        ),
        migrations.DeleteModel(
            name='LikesAndViews',
        ),
        migrations.AddField(
            model_name='likesandviewsmodel',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelItr', to='api.mlmodel'),
        ),
        migrations.AddField(
            model_name='likesandviewsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelItr', to='api.generaluser'),
        ),
        migrations.AlterUniqueTogether(
            name='likesandviewsmodel',
            unique_together={('user', 'model')},
        ),
    ]
